import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About BMI Checks | bmichecks.com",
  description: "Learn about BMI Checks — who runs it, how content is written and reviewed, and our commitment to accurate, responsible health information."
};

export default function AboutPage() {
  return (
    <main className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8">
      <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-line sm:p-10">
        <h1 className="text-4xl font-black text-ink">About BMI Checks</h1>
        <p className="mt-2 text-sm font-semibold text-muted">Last reviewed: April 25, 2026</p>

        <div className="mt-8 space-y-8 leading-8 text-slate-700">

          <section>
            <h2 className="text-2xl font-black text-ink">What is BMI Checks?</h2>
            <p className="mt-3">
              BMI Checks is a free online health utility that helps adults quickly calculate their
              Body Mass Index using either metric or US units. The site provides the BMI number, the
              adult screening category, and an approximate healthy weight range, alongside plain-language
              educational content explaining what BMI means, how it is calculated, and where it has
              limitations.
            </p>
            <p className="mt-3">
              The goal is simple: give people a reliable, fast, and accessible tool that respects their
              privacy, works on any device, and presents health information responsibly — without
              overstating what a single calculation can tell you.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-ink">Who runs this site?</h2>
            <p className="mt-3">
              BMI Checks is owned and managed by Ricardo Diaz, an independent web developer based in
              the United Kingdom. The site is built with Next.js and hosted on Netlify. There is no
              team of medical staff behind this site — it is an independent utility project, and all
              health content is written to reflect widely accepted public health guidance from
              organisations such as the WHO, CDC, and NHS.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-ink">How content is written and reviewed</h2>
            <p className="mt-3">
              All educational content on BMI Checks is written originally by the site owner and
              cross-referenced against publicly available guidance from authoritative health bodies,
              including the World Health Organization (WHO), the Centers for Disease Control and
              Prevention (CDC), and the UK National Health Service (NHS).
            </p>
            <p className="mt-3">
              No content on this site is generated by AI and published without human review. Pages are
              checked for factual accuracy before publication. When public health guidance changes, the
              relevant pages are updated to reflect the current consensus.
            </p>
            <p className="mt-3">
              BMI Checks does not employ clinical staff and cannot provide personalised medical advice.
              Every page includes a clear disclaimer directing users to consult a qualified healthcare
              provider for personal health concerns.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-ink">Update schedule</h2>
            <p className="mt-3">
              The BMI calculator tool is reviewed and tested regularly to ensure calculations remain
              accurate. Educational content is reviewed at least once per year or whenever significant
              changes to public health guidance are published by major health authorities.
              The last full content review was completed in April 2026.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-ink">Corrections and feedback</h2>
            <p className="mt-3">
              If you spot an error, outdated information, or have a suggestion for improving the site,
              please get in touch. Corrections are taken seriously and addressed promptly.
            </p>
            <p className="mt-3">
              Contact:{" "}
              <a
                href="mailto:contact@bmichecks.com"
                className="font-semibold text-teal-700 underline-offset-4 hover:underline"
              >
                contact@bmichecks.com
              </a>
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-ink">Medical disclaimer</h2>
            <p className="mt-3 rounded-2xl border border-coral/30 bg-coral/10 p-4 text-slate-800">
              All content on BMI Checks is for general informational purposes only. It does not
              constitute medical advice, diagnosis, or treatment. Always consult a qualified healthcare
              provider before making decisions about your health.
            </p>
          </section>

        </div>
      </div>
    </main>
  );
}
